int seen;
int last_ttl;
int ttl_change;
struct Packet {
  int sport;
  int rdata;
  int ttl;
  int id;
  int _br_tmp0;
  int _br_tmp1;
  int _br_tmp2;
  int _br_tmp3;
  int _br_tmp4;
  int last_ttl0;
  int ttl_change0;
  int seen0;
  int last_ttl00;
  int ttl_change00;
  int seen00;
  int id0;
  int _br_tmp00;
  int _br_tmp10;
  int _br_tmp20;
  int last_ttl01;
  int ttl_change01;
  int _br_tmp30;
  int _br_tmp40;
  int seen01;
  int last_ttl02;
  int ttl_change02;
  int _br_tmp5;
  int _br_tmp6;
};
void func(struct Packet p) {
  p.last_ttl00 = last_ttl;
  p.ttl_change00 = ttl_change;
  p.seen00 = seen;
  p.id0 = p.rdata;
  p._br_tmp00 = !((p.seen00 == 0));
  p._br_tmp10 = !(p.seen00 == 0);
  p._br_tmp20 = p.last_ttl00 != p.ttl;
  p._br_tmp5 = !((p.seen00 == 0)) && !(p.seen00 == 0) && p.last_ttl00 != p.ttl;
  p.last_ttl01 = p._br_tmp5 ? (p.ttl) : (p.last_ttl00);
  p.ttl_change01 = p._br_tmp5 ? (1) : (p.ttl_change00);
  p._br_tmp30 = p.seen00 == 0;
  p._br_tmp40 = p.seen00 == 0;
  p._br_tmp6 = p.seen00 == 0;
  p.seen01 = p._br_tmp6 ? (1) : (p.seen00);
  p.last_ttl02 = p._br_tmp6 ? (p.ttl) : (p.last_ttl01);
  p.ttl_change02 = p._br_tmp6 ? (0) : (p.ttl_change01);
  last_ttl = p.last_ttl02;
  ttl_change = p.ttl_change02;
  seen = p.seen01;
}
